### ISSUE TITLE
[CANDIDATO] - CANDIDATURA

### ISSUE THREAD

**Issue by wandersonDeve** [SouJunior/vagas-backend#129]

**Comment by caiquefonseca** [comment]
@wandersonDeve , caso a Task tenha sido finalizada, pode passar para waiting test.

**Comment by caiquefonseca** [comment]
- [ ] Filtro de busca -> falta filtrar por local, falta filtrar o tipo de vaga (híbrido, remoto ou presencial)
- [ ] (backend precisa criar a rota)
- [ ] Exibir dados da empresa -> falta exibir foto e nome da empresa
- [ ] candidatura do usuário -> falta rota para enviar currículo quando clicar no botão "Me Candidatar" 
- [ ] Receber e xibir currículo -> consegue colocar mais de 2 cv, não consegue deletar e aparece um número na parte da frente no nome do arquivo do CV
