### ISSUE TITLE
5. Cadastro de Usuário - M

### ISSUE THREAD

**Issue by jsalgues** [SouJunior/vagas-backend#53]
**Definição**:

Como usuário, eu gostaria de realizar o cadastro no Portal de Vagas, para que possa dar prosseguimento às candidaturas

**Descrição:**

Para que o usuário possa prosseguir a interação com a SouJunior, é necessário que o login seja feito.

**Protótipo:**

![Image](https://user-images.githubusercontent.com/57487476/198881747-63b1ad1e-1fcd-4bfd-8704-3d3e5c2cde3a.jpeg)

**Critérios de Aceite:** (part. Vic Knust)

- VISÃO GERAL
  - Logo estática SouJunior à esquerda
  - Dados
  - Campo “Nome completo”
  - Campo “CPF”
  - Campo “E-mail”
  - Campo “Senha”
  - Checkbox “Aceite de termos”
  - Opção “Criar conta”
  - Opção “Já tem login”

- TODOS OS CAMPOS/CHECKBOX ABAIXO SÃO OBRIGATÓRIOS
- CAMPO NOME COMPLETO 
  - O campo “Nome completo” deve ter limite de 30 caracteres
  - O sistema não deve permitir mais do que os 30 caracteres
- CAMPO CPF
  - Quando o usuário inserir os dados, o sistema aplicará a seguinte mascara: XXX.XXX.XXX-XX
  - O campo CPF deve ser preenchido somente com número
  - O sistema deve validar o CPF de acordo com os critérios da RF
  - Caso critério não seja cumprido, imprimir CPF inválido
- CAMPO E-MAIL
    - Quando o usuário digitar o e-mail, o sistema só poderá aceitar a formatação [xx@domínio]
      - Caso esteja em formatação correta, o sistema deve verificar se o e-mail já se encontra na base de dados da SouJunior
      - Caso positivo, retornar a mensagem que o e-mail já foi cadastrado e solicitando que o usuário faça login
- CAMPO SENHA
  - Quando o usuário inserir os dados, o sistema só poderá aceitar a senha que tiver:
    - Mínimo oito caracteres
    - Letras minúsculas e/ou maiúsculas
    - Números e/ou caracteres especiais
  - Caso critério não seja cumprido, imprimir mensagem de erro abaixo do campo e pintar os caracteres campo de vermelho
- CHECKBOX ACEITE DE TERMOS
  - Ao lado de checkbox, imprimir a mensagem “Li e aceito os Termos e Política de Privacidade da SouJunior”
    - A palavra “Termos” deverá ser uma opção para o usuário, a qual o direciona para um pdf com os termos da plataforma
      - Verificar com jurídico
    - A palavra “Política de Privacidade” deverá ser uma opção para o usuário, a qual o direciona para um pdf com os termos da plataforma
      - Verificar com jurídico
  - Quando o usuário marcar o checkbox, destacar checkbox para que usuário entenda que ação foi executada e ele aceitou termos e política de privacidade.
- OPÇÃO CRIAR CONTA
  - Caso o usuário tenha preenchido todos os campos e os mesmos estejam validados pelo sistema, disponibilizar a opção “Criar conta”
  - Caso negativo, não disponibilizar opção
  - Ao clicar na opção "Criar conta":
    - Sistema deverá executará US_Confirmação_de_e-mail
- OPÇÃO JÁ TEM LOGIN
  - Abaixo da opção “Criar conta”, imprimir “Já tem conta? Faça login”
    - A palavra login será uma opção, que sempre ficará disponível para clique de usuário
      - Caso o usuário clique, executar US_Login

**Comment by allbertuu** [comment]
### Reunião Frontend Vagas - 21/12
Conversando com a equipe de Frontend, notamos que há diferenças entre o protótipo de UI/UX, e o que está sendo pedido pela equipe de APM - Vagas.

Seguindo o fluxo padrão, pedimos que a equipe de UI/UX nos dê uma devolutiva se pretende seguir como está no Figma, ou adicionará outras informações (até então ausentes) como: campo de CPF, e aceitar os termos de privacidade.
