### ISSUE TITLE
Adição de novas tabelas e remoção das solicitadas

### ISSUE THREAD

**Issue by Fla-code** [SouJunior/vagas-backend#70]
Descrição:

Ajustes no banco de dados com adição de novas tabelas e a remoção de tabelas sugerida pelo time data para deixar o banco de dados mais simplificado.

![Image](https://user-images.githubusercontent.com/95653155/219969451-4676dc45-b3c0-4b76-abd3-52467fe0edfb.png)

**Comment by Fla-code** [comment]
https://github.com/orgs/SouJunior/projects/3/views/1?pane=issue&itemId=13416739

Definição:

Como empresa, eu esqueci minha senha e gostaria de redefini-la, para que eu possa acessar a área empresa e cadastrar as minhas vagas disponíveis.

Descrição:

Para que o usuário possa redefinir sua senha, caso se esqueça, ele deve ir até a área de Login, clicar em "esqueci a senha" e cadastrar uma nova. Após todos os processos de redefinição que envolverá alguns critérios de segurança, o usuário estará apto para acessar sua conta novamente.

**Comment by Fla-code** [comment]
@Amaro13 @Joanadarknes @

**Comment by wandersonDeve** [comment]
@Jacqueline2021  Favor validar os dados salvos para as empresas, caso haja a necessidade de mudança, já mudo nessa sprint
