### ISSUE TITLE
[Candidato] - Feed de vagas

### ISSUE THREAD

**Issue by wandersonDeve** [SouJunior/vagas-backend#87]

**Comment by caiquefonseca** [comment]
@wandersonDeve Essa Task está pronta?
Se sim, pode mover para Waiting Test.

**Comment by FernandoMiguelS** [comment]
Boa noite, qual seria a descrição dessa task?

**Comment by FernandoMiguelS** [comment]
Como não tive retorno, e por ser a task mais antiga, podemos finalizar?  

@caiquefonseca
